# Opacity window rules
windowrule = opacity 0.96 override 0.86 override, match:class ^(Alacritty)$
windowrule = opacity 1 override 0.92 override, match:class ^(spotify)$
windowrule = opacity 1 override 0.92 override, match:class ^(elecwhat)$

# file picker fixes
windowrule = match:title ^(Open File|Save File|Open Folder|Choose Files)$, float on, center on, size 70% 75%

