exec-once = waybar
exec-once = alacritty
exec-once = sleep 2 && hyprpaper
exec-once = hyprsunset
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/ws-history.sh daemon
exec-once = hypridle
exec-once = pywalfox start
exec-once = dbus-update-activation-environment --all
exec-once = nm-applet --indicator
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
