exec-once = waybar
exec-once = alacritty
exec-once = hyprpaper
exec-once = sh -c "sleep 2; ~/.config/hypr/scripts/hyprpaper-all.sh"
exec-once = hyprsunset
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/ws-history.sh daemon
exec-once = hypridle
exec-once = pywalfox start
