# Launcher + apps
bind = $mod, RETURN, exec, alacritty
bind = $mod, B, exec, firefox
bind = $mod, F, exec, dolphin
bind = $mod, S, exec, rofi -show drun
bind = $mod, P, exec, ~/.config/hypr/scripts/reload.sh
bind = $mod, W, exec, ~/.config/hypr/scripts/apply-theme.sh
bind = $mod, Tab, exec, ~/.config/hypr/scripts/app-switcher.sh

# Lock Hyprland
bind = $mod, X, exec, hyprlock

# Clipboard Manager
bind = $mod SHIFT, V, exec, /home/nlion/.config/hypr/scripts/cliphist-rofi-img.sh | wl-copy

# Screenshots
bind = $mod SHIFT, S, exec, hyprshot -m region --clipboard-only
bind = $mod CTRL, S, exec, hyprshot -m window --clipboard-only

# Window handling
bind = $mod, Q, killactive
bind = $mod, V, togglefloating

bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Resize mode
bind = $mod, R, submap, resize
submap = resize
binde = , right, resizeactive, 30 -1
binde = , left, resizeactive, -30 0
binde = , up, resizeactive, 0 -30
binde = , down, resizeactive, 0 30
bind = , escape, submap, reset
submap = reset

# Workspaces 1-10
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Move active window to workspace 1-10
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Global workspace navigation
bind = $mod, mouse_down, workspace, r+0
bind = $mod, mouse_up, workspace, r-1
bind = $mod, right, workspace, r+1
bind = $mod, left, workspace, r-1

# Local workspace navigation on the current monitor
bind = $mod SHIFT, right, workspace, m+1
bind = $mod SHIFT, left, workspace, m-1

# Move windows
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, r

# Jump to next empty workspace on the current monitor
bind = $mod, N, workspace, emptynm

# Send active window to next empty workspace on the current monitor
bind = $mod SHIFT, N, movetoworkspace, emptynm

# Jump to previous workspace
bind = $mod, M, exec, ~/.config/hypr/scripts/ws-history.sh back

# Jump to previous workspace and follow it
bind = $mod SHIFT, M, exec, ~/.config/hypr/scripts/ws-history.sh move-back-follow

# Media keys
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next

