general {
    gaps_in = 2
    gaps_out = 3
    border_size = 2
    col.active_border = rgba(cba6f7ee) rgba(8b5cf6ee) 45deg
    col.inactive_border = rgba(7c7f93aa)
}

xwayland {
    force_zero_scaling = true
}

