general {
    col.active_border        = rgba({color5.strip}ee) rgba({color13.strip}ee) 45deg
    col.inactive_border      = rgba({background.strip}99)
    col.nogroup_border       = rgba({color1.strip}dd)
    col.nogroup_border_active = rgba({color5.strip}ee)
}

group {
    col.border_active          = rgba({color5.strip}ee)
    col.border_inactive        = rgba({background.strip}99)
    col.border_locked_active   = rgba({color13.strip}ee)
    col.border_locked_inactive = rgba({color1.strip}99)

    groupbar {
        col.active          = rgba({color5.strip}ff)
        col.inactive        = rgba({background.strip}ff)
        col.locked_active   = rgba({color13.strip}ff)
        col.locked_inactive = rgba({color1.strip}ff)
    }
}