[pywal]
; Sleek Theme for pywal

text               = {color5.strip}
subtext            = {color7.strip}
nav-active-text    = {background.strip}
main               = {background.strip}
sidebar            = {background.strip}
player             = {background.strip}
card               = {background.strip}
shadow             = {color0.strip}
main-secondary     = {color0.strip}
button             = {color5.strip}
button-secondary   = {color5.strip}
button-active      = {color13.strip}
button-disabled    = {color8.strip}
nav-active         = {color13.strip}
play-button        = {color5.strip}
tab-active         = {color0.strip}
notification       = {color8.strip}
notification-error = {color8.strip}
playback-bar       = {color5.strip}
misc               = FFFFFF